In [1]:
#Main Implementation of solving sudoku

import numpy as np
import time

def solve(sudoku, row=0, column=0, GUISupport=False):
    if column >= len(sudoku):
        row += 1
        column = 0
    if row >= len(sudoku):
        return True;
    currentNum = None
    if GUISupport:
        currentNum = int(sudoku[row][column].get())
    else:
        currentNum = sudoku[row][column]
    if currentNum != 0:
        solved = solve(sudoku, row, column+1, GUISupport)
        return solved

    for i in range(1, 10):
        found = searchHorizontal(sudoku, row, i, GUISupport)
        if found:
            continue
        found = searchVertical(sudoku, column, i, GUISupport)
        if found:
            continue
        found = searchSubgrid(sudoku, row, column, i, GUISupport)
        if found:
            continue
        if GUISupport:
            sudoku[row][column].set(i)
            time.sleep(0.1)
        else:
            sudoku[row][column] = i
        solved = solve(sudoku, row, column+1, GUISupport)
        if not solved:
            if GUISupport:
                sudoku[row][column].set(0)
                time.sleep(0.1)
            else:
                sudoku[row][column] = 0
        else:
            return True
    return False

def searchHorizontal(sudoku, row, number, GUISupport=False):
    for i in range(len(sudoku)):
        if GUISupport:
            if int(sudoku[row][i].get()) == number:
                return True
        else:
            if sudoku[row][i] == number:
                return True
    return False

def searchVertical(sudoku, column, number, GUISupport=False):
    for i in range(len(sudoku)):
        if GUISupport:
            if int(sudoku[i][column].get()) == number:
                return True
        else:
            if sudoku[i][column] == number:
                return True
    return False

def searchSubgrid(sudoku, row, column, number, GUISupport=False):
    leftoverRow = row % 3
    leftoverColumn = column % 3
    subgridRow = row-leftoverRow
    subgridColumn = column - leftoverColumn
    for i in range(subgridRow, subgridRow+3):
        for j in range(subgridColumn, subgridColumn+3):
            if GUISupport:
                if int(sudoku[row][i].get()) == number:
                    return True
            else:
                if(sudoku[i][j] == number):
                    return True
    return False
    
def main():
    sudoku = [[0,0,0,2,6,0,7,0,1],
              [6,8,0,0,7,0,0,9,0],
              [1,9,0,0,0,4,5,0,0],
              [8,2,0,1,0,0,0,4,0],
              [0,0,4,6,0,2,9,0,0],
              [0,5,0,0,0,3,0,2,8],
              [0,0,9,3,0,0,0,7,4],
              [0,4,0,0,5,0,0,3,6],
              [7,0,3,0,1,8,0,0,0]]
    solve(sudoku)
    print(np.matrix(sudoku))

main()



[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]


In [2]:
#GUI for sudoku solver

from tkinter import *
from tkinter import ttk
import _thread

def startGUI(sudoku):
    main=Tk()
    main.title("Sudoku Solver")
    mainFrame = ttk.Frame(main)
    mainFrame.grid(row=0, column=0)
    for i in range(9):
        for j in range(9):
            number = StringVar()
            number.set(sudoku[i][j])
            sudoku[i][j] = number
            frame = ttk.Frame(mainFrame, borderwidth=2, relief='solid', width=75, height=75)
            frame.grid(row=i, column=j, fill=None)
            frame.pack_propagate(0)
            numbersLabel = ttk.Label(frame, textvariable=sudoku[i][j], font=("Calibri",32))
            numbersLabel.place(relx=0.5,rely=0.5, anchor=CENTER)
    start = ttk.Button(main, text='Solve!', command= lambda: solveGUI(sudoku), width=75)
    start.grid(row=1, column=0, pady=15)
    main.mainloop()

def solveGUI(sudokuBoard):
    try:
        _thread.start_new_thread( solve, (sudokuBoard,0,0, True) )
    except:
        print ("Error: unable to start thread")
    
sudoku = [[0,0,0,2,6,0,7,0,1],
          [6,8,0,0,7,0,0,9,0],
          [1,9,0,0,0,4,5,0,0],
          [8,2,0,1,0,0,0,4,0],
          [0,0,4,6,0,2,9,0,0],
          [0,5,0,0,0,3,0,2,8],
          [0,0,9,3,0,0,0,7,4],
          [0,4,0,0,5,0,0,3,6],
          [7,0,3,0,1,8,0,0,0]]
startGUI(sudoku)